DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    po_item TEXT NOT NULL,
    catalog_item_id TEXT NOT NULL,
    catalog_item_description TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON TABLE orders TO public;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO public; 